<?php
/**
 * BlogToSocialResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PostBoostClient\Model;

use \ArrayAccess;
use \PostBoostClient\ObjectSerializer;

/**
 * BlogToSocialResponse Class Doc Comment
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BlogToSocialResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BlogToSocialResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'blog_title' => 'string',
        'blog_excerpt' => 'string',
        'captions' => '\PostBoostClient\Model\BlogToSocialCaption[]',
        'post_uuid' => 'string',
        'media' => '\PostBoostClient\Model\BlogToSocialMedia',
        'credits_used' => 'int',
        'credits_remaining' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'blog_title' => null,
        'blog_excerpt' => null,
        'captions' => null,
        'post_uuid' => 'uuid',
        'media' => null,
        'credits_used' => null,
        'credits_remaining' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'blog_title' => false,
        'blog_excerpt' => false,
        'captions' => false,
        'post_uuid' => false,
        'media' => false,
        'credits_used' => false,
        'credits_remaining' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blog_title' => 'blog_title',
        'blog_excerpt' => 'blog_excerpt',
        'captions' => 'captions',
        'post_uuid' => 'post_uuid',
        'media' => 'media',
        'credits_used' => 'credits_used',
        'credits_remaining' => 'credits_remaining'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blog_title' => 'setBlogTitle',
        'blog_excerpt' => 'setBlogExcerpt',
        'captions' => 'setCaptions',
        'post_uuid' => 'setPostUuid',
        'media' => 'setMedia',
        'credits_used' => 'setCreditsUsed',
        'credits_remaining' => 'setCreditsRemaining'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blog_title' => 'getBlogTitle',
        'blog_excerpt' => 'getBlogExcerpt',
        'captions' => 'getCaptions',
        'post_uuid' => 'getPostUuid',
        'media' => 'getMedia',
        'credits_used' => 'getCreditsUsed',
        'credits_remaining' => 'getCreditsRemaining'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('blog_title', $data ?? [], null);
        $this->setIfExists('blog_excerpt', $data ?? [], null);
        $this->setIfExists('captions', $data ?? [], null);
        $this->setIfExists('post_uuid', $data ?? [], null);
        $this->setIfExists('media', $data ?? [], null);
        $this->setIfExists('credits_used', $data ?? [], null);
        $this->setIfExists('credits_remaining', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blog_title
     *
     * @return string|null
     */
    public function getBlogTitle()
    {
        return $this->container['blog_title'];
    }

    /**
     * Sets blog_title
     *
     * @param string|null $blog_title The blog post title (scraped or provided directly).
     *
     * @return self
     */
    public function setBlogTitle($blog_title)
    {
        if (is_null($blog_title)) {
            throw new \InvalidArgumentException('non-nullable blog_title cannot be null');
        }
        $this->container['blog_title'] = $blog_title;

        return $this;
    }

    /**
     * Gets blog_excerpt
     *
     * @return string|null
     */
    public function getBlogExcerpt()
    {
        return $this->container['blog_excerpt'];
    }

    /**
     * Sets blog_excerpt
     *
     * @param string|null $blog_excerpt A short excerpt from the blog post content.
     *
     * @return self
     */
    public function setBlogExcerpt($blog_excerpt)
    {
        if (is_null($blog_excerpt)) {
            throw new \InvalidArgumentException('non-nullable blog_excerpt cannot be null');
        }
        $this->container['blog_excerpt'] = $blog_excerpt;

        return $this;
    }

    /**
     * Gets captions
     *
     * @return \PostBoostClient\Model\BlogToSocialCaption[]|null
     */
    public function getCaptions()
    {
        return $this->container['captions'];
    }

    /**
     * Sets captions
     *
     * @param \PostBoostClient\Model\BlogToSocialCaption[]|null $captions Generated captions, one per target account.
     *
     * @return self
     */
    public function setCaptions($captions)
    {
        if (is_null($captions)) {
            throw new \InvalidArgumentException('non-nullable captions cannot be null');
        }
        $this->container['captions'] = $captions;

        return $this;
    }

    /**
     * Gets post_uuid
     *
     * @return string|null
     */
    public function getPostUuid()
    {
        return $this->container['post_uuid'];
    }

    /**
     * Sets post_uuid
     *
     * @param string|null $post_uuid UUID of the created draft post. Only present when `create_post` was `true`.
     *
     * @return self
     */
    public function setPostUuid($post_uuid)
    {
        if (is_null($post_uuid)) {
            throw new \InvalidArgumentException('non-nullable post_uuid cannot be null');
        }
        $this->container['post_uuid'] = $post_uuid;

        return $this;
    }

    /**
     * Gets media
     *
     * @return \PostBoostClient\Model\BlogToSocialMedia|null
     */
    public function getMedia()
    {
        return $this->container['media'];
    }

    /**
     * Sets media
     *
     * @param \PostBoostClient\Model\BlogToSocialMedia|null $media media
     *
     * @return self
     */
    public function setMedia($media)
    {
        if (is_null($media)) {
            throw new \InvalidArgumentException('non-nullable media cannot be null');
        }
        $this->container['media'] = $media;

        return $this;
    }

    /**
     * Gets credits_used
     *
     * @return int|null
     */
    public function getCreditsUsed()
    {
        return $this->container['credits_used'];
    }

    /**
     * Sets credits_used
     *
     * @param int|null $credits_used Number of AI credits consumed by this request (one per successful caption).
     *
     * @return self
     */
    public function setCreditsUsed($credits_used)
    {
        if (is_null($credits_used)) {
            throw new \InvalidArgumentException('non-nullable credits_used cannot be null');
        }
        $this->container['credits_used'] = $credits_used;

        return $this;
    }

    /**
     * Gets credits_remaining
     *
     * @return int|null
     */
    public function getCreditsRemaining()
    {
        return $this->container['credits_remaining'];
    }

    /**
     * Sets credits_remaining
     *
     * @param int|null $credits_remaining Remaining AI credits for the current billing period. `null` for unlimited plans.
     *
     * @return self
     */
    public function setCreditsRemaining($credits_remaining)
    {
        if (is_null($credits_remaining)) {
            throw new \InvalidArgumentException('non-nullable credits_remaining cannot be null');
        }
        $this->container['credits_remaining'] = $credits_remaining;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


