<?php
/**
 * BlogToSocialInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PostBoostClient\Model;

use \ArrayAccess;
use \PostBoostClient\ObjectSerializer;

/**
 * BlogToSocialInput Class Doc Comment
 *
 * @category Class
 * @description At least one of &#x60;url&#x60; or (&#x60;title&#x60; + &#x60;excerpt&#x60;) must be provided. If both are given, direct values take priority over the scraped URL content.
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BlogToSocialInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BlogToSocialInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'url' => 'string',
        'title' => 'string',
        'excerpt' => 'string',
        'image_url' => 'string',
        'platforms' => 'string[]',
        'account_ids' => 'int[]',
        'tone' => 'string',
        'content_length' => 'string',
        'hashtags' => 'string',
        'cta' => 'string',
        'language' => 'string',
        'custom_instructions' => 'string',
        'create_post' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'url' => 'uri',
        'title' => null,
        'excerpt' => null,
        'image_url' => 'uri',
        'platforms' => null,
        'account_ids' => null,
        'tone' => null,
        'content_length' => null,
        'hashtags' => null,
        'cta' => null,
        'language' => null,
        'custom_instructions' => null,
        'create_post' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'url' => false,
        'title' => false,
        'excerpt' => false,
        'image_url' => false,
        'platforms' => false,
        'account_ids' => false,
        'tone' => false,
        'content_length' => false,
        'hashtags' => false,
        'cta' => false,
        'language' => false,
        'custom_instructions' => false,
        'create_post' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'url' => 'url',
        'title' => 'title',
        'excerpt' => 'excerpt',
        'image_url' => 'image_url',
        'platforms' => 'platforms',
        'account_ids' => 'account_ids',
        'tone' => 'tone',
        'content_length' => 'content_length',
        'hashtags' => 'hashtags',
        'cta' => 'cta',
        'language' => 'language',
        'custom_instructions' => 'custom_instructions',
        'create_post' => 'create_post'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'url' => 'setUrl',
        'title' => 'setTitle',
        'excerpt' => 'setExcerpt',
        'image_url' => 'setImageUrl',
        'platforms' => 'setPlatforms',
        'account_ids' => 'setAccountIds',
        'tone' => 'setTone',
        'content_length' => 'setContentLength',
        'hashtags' => 'setHashtags',
        'cta' => 'setCta',
        'language' => 'setLanguage',
        'custom_instructions' => 'setCustomInstructions',
        'create_post' => 'setCreatePost'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'url' => 'getUrl',
        'title' => 'getTitle',
        'excerpt' => 'getExcerpt',
        'image_url' => 'getImageUrl',
        'platforms' => 'getPlatforms',
        'account_ids' => 'getAccountIds',
        'tone' => 'getTone',
        'content_length' => 'getContentLength',
        'hashtags' => 'getHashtags',
        'cta' => 'getCta',
        'language' => 'getLanguage',
        'custom_instructions' => 'getCustomInstructions',
        'create_post' => 'getCreatePost'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PLATFORMS_FACEBOOK = 'facebook';
    public const PLATFORMS_INSTAGRAM = 'instagram';
    public const PLATFORMS_X = 'x';
    public const PLATFORMS_LINKEDIN = 'linkedin';
    public const PLATFORMS_PINTEREST = 'pinterest';
    public const PLATFORMS_YOUTUBE = 'youtube';
    public const PLATFORMS_TIKTOK = 'tiktok';
    public const PLATFORMS_MASTODON = 'mastodon';
    public const PLATFORMS_THREADS = 'threads';
    public const PLATFORMS_BLUESKY = 'bluesky';
    public const PLATFORMS_GOOGLE_BUSINESS = 'google_business';
    public const TONE_NEUTRAL = 'neutral';
    public const TONE_FRIENDLY = 'friendly';
    public const TONE_FORMAL = 'formal';
    public const TONE_EDGY = 'edgy';
    public const TONE_ENGAGING = 'engaging';
    public const TONE_CASUAL = 'casual';
    public const TONE_PROFESSIONAL = 'professional';
    public const TONE_HUMOROUS = 'humorous';
    public const TONE_INSPIRATIONAL = 'inspirational';
    public const TONE_CONVERSATIONAL = 'conversational';
    public const CONTENT_LENGTH_SHORT = 'short';
    public const CONTENT_LENGTH_MEDIUM = 'medium';
    public const CONTENT_LENGTH_LONG = 'long';
    public const HASHTAGS_NONE = 'none';
    public const HASHTAGS_FEW = 'few';
    public const HASHTAGS_SOME = 'some';
    public const HASHTAGS_MANY = 'many';
    public const CTA_NONE = 'none';
    public const CTA_QUESTION = 'question';
    public const CTA_LINK = 'link';
    public const CTA_SUBSCRIBE = 'subscribe';
    public const CTA_FOLLOW = 'follow';
    public const CTA_SHARE = 'share';
    public const CTA_LEARN_MORE = 'learn_more';
    public const CTA_SIGNUP = 'signup';
    public const CTA_BUY = 'buy';
    public const CTA_DOWNLOAD = 'download';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPlatformsAllowableValues()
    {
        return [
            self::PLATFORMS_FACEBOOK,
            self::PLATFORMS_INSTAGRAM,
            self::PLATFORMS_X,
            self::PLATFORMS_LINKEDIN,
            self::PLATFORMS_PINTEREST,
            self::PLATFORMS_YOUTUBE,
            self::PLATFORMS_TIKTOK,
            self::PLATFORMS_MASTODON,
            self::PLATFORMS_THREADS,
            self::PLATFORMS_BLUESKY,
            self::PLATFORMS_GOOGLE_BUSINESS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getToneAllowableValues()
    {
        return [
            self::TONE_NEUTRAL,
            self::TONE_FRIENDLY,
            self::TONE_FORMAL,
            self::TONE_EDGY,
            self::TONE_ENGAGING,
            self::TONE_CASUAL,
            self::TONE_PROFESSIONAL,
            self::TONE_HUMOROUS,
            self::TONE_INSPIRATIONAL,
            self::TONE_CONVERSATIONAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getContentLengthAllowableValues()
    {
        return [
            self::CONTENT_LENGTH_SHORT,
            self::CONTENT_LENGTH_MEDIUM,
            self::CONTENT_LENGTH_LONG,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getHashtagsAllowableValues()
    {
        return [
            self::HASHTAGS_NONE,
            self::HASHTAGS_FEW,
            self::HASHTAGS_SOME,
            self::HASHTAGS_MANY,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCtaAllowableValues()
    {
        return [
            self::CTA_NONE,
            self::CTA_QUESTION,
            self::CTA_LINK,
            self::CTA_SUBSCRIBE,
            self::CTA_FOLLOW,
            self::CTA_SHARE,
            self::CTA_LEARN_MORE,
            self::CTA_SIGNUP,
            self::CTA_BUY,
            self::CTA_DOWNLOAD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('excerpt', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('platforms', $data ?? [], null);
        $this->setIfExists('account_ids', $data ?? [], null);
        $this->setIfExists('tone', $data ?? [], 'engaging');
        $this->setIfExists('content_length', $data ?? [], 'medium');
        $this->setIfExists('hashtags', $data ?? [], 'few');
        $this->setIfExists('cta', $data ?? [], 'none');
        $this->setIfExists('language', $data ?? [], 'auto');
        $this->setIfExists('custom_instructions', $data ?? [], null);
        $this->setIfExists('create_post', $data ?? [], false);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['url']) && (mb_strlen($this->container['url']) > 2000)) {
            $invalidProperties[] = "invalid value for 'url', the character length must be smaller than or equal to 2000.";
        }

        if (!is_null($this->container['title']) && (mb_strlen($this->container['title']) > 500)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['excerpt']) && (mb_strlen($this->container['excerpt']) > 5000)) {
            $invalidProperties[] = "invalid value for 'excerpt', the character length must be smaller than or equal to 5000.";
        }

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) > 2000)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be smaller than or equal to 2000.";
        }

        $allowedValues = $this->getToneAllowableValues();
        if (!is_null($this->container['tone']) && !in_array($this->container['tone'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tone', must be one of '%s'",
                $this->container['tone'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getContentLengthAllowableValues();
        if (!is_null($this->container['content_length']) && !in_array($this->container['content_length'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'content_length', must be one of '%s'",
                $this->container['content_length'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getHashtagsAllowableValues();
        if (!is_null($this->container['hashtags']) && !in_array($this->container['hashtags'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'hashtags', must be one of '%s'",
                $this->container['hashtags'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCtaAllowableValues();
        if (!is_null($this->container['cta']) && !in_array($this->container['cta'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'cta', must be one of '%s'",
                $this->container['cta'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['language']) && (mb_strlen($this->container['language']) > 10)) {
            $invalidProperties[] = "invalid value for 'language', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['custom_instructions']) && (mb_strlen($this->container['custom_instructions']) > 500)) {
            $invalidProperties[] = "invalid value for 'custom_instructions', the character length must be smaller than or equal to 500.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url Blog post URL to scrape. Required if `title` and `excerpt` are not provided.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        if ((mb_strlen($url) > 2000)) {
            throw new \InvalidArgumentException('invalid length for $url when calling BlogToSocialInput., must be smaller than or equal to 2000.');
        }

        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Blog post title. Required if `url` is not provided.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        if ((mb_strlen($title) > 500)) {
            throw new \InvalidArgumentException('invalid length for $title when calling BlogToSocialInput., must be smaller than or equal to 500.');
        }

        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets excerpt
     *
     * @return string|null
     */
    public function getExcerpt()
    {
        return $this->container['excerpt'];
    }

    /**
     * Sets excerpt
     *
     * @param string|null $excerpt Blog post summary or excerpt. Required if `url` is not provided.
     *
     * @return self
     */
    public function setExcerpt($excerpt)
    {
        if (is_null($excerpt)) {
            throw new \InvalidArgumentException('non-nullable excerpt cannot be null');
        }
        if ((mb_strlen($excerpt) > 5000)) {
            throw new \InvalidArgumentException('invalid length for $excerpt when calling BlogToSocialInput., must be smaller than or equal to 5000.');
        }

        $this->container['excerpt'] = $excerpt;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url Featured image URL for the blog post. When `create_post` is `true`, the image is imported into the workspace media library and attached to the draft post. If omitted in URL mode, the scraper attempts to extract the `og:image` meta tag.
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            throw new \InvalidArgumentException('non-nullable image_url cannot be null');
        }
        if ((mb_strlen($image_url) > 2000)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling BlogToSocialInput., must be smaller than or equal to 2000.');
        }

        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets platforms
     *
     * @return string[]|null
     */
    public function getPlatforms()
    {
        return $this->container['platforms'];
    }

    /**
     * Sets platforms
     *
     * @param string[]|null $platforms Target social media platforms. Only connected accounts matching these platforms are used. If omitted, all connected accounts in the workspace are targeted.
     *
     * @return self
     */
    public function setPlatforms($platforms)
    {
        if (is_null($platforms)) {
            throw new \InvalidArgumentException('non-nullable platforms cannot be null');
        }
        $allowedValues = $this->getPlatformsAllowableValues();
        if (array_diff($platforms, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'platforms', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['platforms'] = $platforms;

        return $this;
    }

    /**
     * Gets account_ids
     *
     * @return int[]|null
     */
    public function getAccountIds()
    {
        return $this->container['account_ids'];
    }

    /**
     * Sets account_ids
     *
     * @param int[]|null $account_ids Specific account IDs to generate captions for. Takes precedence over `platforms` when both are provided.
     *
     * @return self
     */
    public function setAccountIds($account_ids)
    {
        if (is_null($account_ids)) {
            throw new \InvalidArgumentException('non-nullable account_ids cannot be null');
        }
        $this->container['account_ids'] = $account_ids;

        return $this;
    }

    /**
     * Gets tone
     *
     * @return string|null
     */
    public function getTone()
    {
        return $this->container['tone'];
    }

    /**
     * Sets tone
     *
     * @param string|null $tone Writing tone for all generated captions.
     *
     * @return self
     */
    public function setTone($tone)
    {
        if (is_null($tone)) {
            throw new \InvalidArgumentException('non-nullable tone cannot be null');
        }
        $allowedValues = $this->getToneAllowableValues();
        if (!in_array($tone, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tone', must be one of '%s'",
                    $tone,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tone'] = $tone;

        return $this;
    }

    /**
     * Gets content_length
     *
     * @return string|null
     */
    public function getContentLength()
    {
        return $this->container['content_length'];
    }

    /**
     * Sets content_length
     *
     * @param string|null $content_length Desired length of the generated captions.
     *
     * @return self
     */
    public function setContentLength($content_length)
    {
        if (is_null($content_length)) {
            throw new \InvalidArgumentException('non-nullable content_length cannot be null');
        }
        $allowedValues = $this->getContentLengthAllowableValues();
        if (!in_array($content_length, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'content_length', must be one of '%s'",
                    $content_length,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['content_length'] = $content_length;

        return $this;
    }

    /**
     * Gets hashtags
     *
     * @return string|null
     */
    public function getHashtags()
    {
        return $this->container['hashtags'];
    }

    /**
     * Sets hashtags
     *
     * @param string|null $hashtags Hashtag quantity: none (0), few (1-3), some (3-5), many (5+).
     *
     * @return self
     */
    public function setHashtags($hashtags)
    {
        if (is_null($hashtags)) {
            throw new \InvalidArgumentException('non-nullable hashtags cannot be null');
        }
        $allowedValues = $this->getHashtagsAllowableValues();
        if (!in_array($hashtags, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'hashtags', must be one of '%s'",
                    $hashtags,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['hashtags'] = $hashtags;

        return $this;
    }

    /**
     * Gets cta
     *
     * @return string|null
     */
    public function getCta()
    {
        return $this->container['cta'];
    }

    /**
     * Sets cta
     *
     * @param string|null $cta Call-to-action type appended to each caption.
     *
     * @return self
     */
    public function setCta($cta)
    {
        if (is_null($cta)) {
            throw new \InvalidArgumentException('non-nullable cta cannot be null');
        }
        $allowedValues = $this->getCtaAllowableValues();
        if (!in_array($cta, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'cta', must be one of '%s'",
                    $cta,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cta'] = $cta;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language Output language as an ISO 639-1 code (e.g. `en`, `de`, `fr`). Use `auto` to match the blog post's language automatically.
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        if ((mb_strlen($language) > 10)) {
            throw new \InvalidArgumentException('invalid length for $language when calling BlogToSocialInput., must be smaller than or equal to 10.');
        }

        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets custom_instructions
     *
     * @return string|null
     */
    public function getCustomInstructions()
    {
        return $this->container['custom_instructions'];
    }

    /**
     * Sets custom_instructions
     *
     * @param string|null $custom_instructions Additional instructions appended to the AI prompt (e.g. \"always mention our free tier\").
     *
     * @return self
     */
    public function setCustomInstructions($custom_instructions)
    {
        if (is_null($custom_instructions)) {
            throw new \InvalidArgumentException('non-nullable custom_instructions cannot be null');
        }
        if ((mb_strlen($custom_instructions) > 500)) {
            throw new \InvalidArgumentException('invalid length for $custom_instructions when calling BlogToSocialInput., must be smaller than or equal to 500.');
        }

        $this->container['custom_instructions'] = $custom_instructions;

        return $this;
    }

    /**
     * Gets create_post
     *
     * @return bool|null
     */
    public function getCreatePost()
    {
        return $this->container['create_post'];
    }

    /**
     * Sets create_post
     *
     * @param bool|null $create_post When `true`, creates a draft post in the workspace with per-account caption versions. If an image is available, it is imported and attached to the post.
     *
     * @return self
     */
    public function setCreatePost($create_post)
    {
        if (is_null($create_post)) {
            throw new \InvalidArgumentException('non-nullable create_post cannot be null');
        }
        $this->container['create_post'] = $create_post;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


