<?php
/**
 * DeleteMode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PostBoostClient\Model;
use \PostBoostClient\ObjectSerializer;

/**
 * DeleteMode Class Doc Comment
 *
 * @category Class
 * @description - &#x60;app_only&#x60; — delete from PostBoost only - &#x60;app_and_social&#x60; — delete from PostBoost and the social platform - &#x60;social_only&#x60; — delete from the social platform only
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeleteMode
{
    /**
     * Possible values of this enum
     */
    public const APP_ONLY = 'app_only';

    public const APP_AND_SOCIAL = 'app_and_social';

    public const SOCIAL_ONLY = 'social_only';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APP_ONLY,
            self::APP_AND_SOCIAL,
            self::SOCIAL_ONLY
        ];
    }
}


