<?php
/**
 * ImageGenerateInput
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PostBoostClient\Model;

use \ArrayAccess;
use \PostBoostClient\ObjectSerializer;

/**
 * ImageGenerateInput Class Doc Comment
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ImageGenerateInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ImageGenerateInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'caption' => 'string',
        'platform' => 'string',
        'template' => 'string',
        'style' => 'string',
        'brand_voice' => 'string',
        'custom_instructions' => 'string',
        'prompt' => 'string',
        'aspect_ratio' => 'string',
        'count' => 'int',
        'quality' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'caption' => null,
        'platform' => null,
        'template' => null,
        'style' => null,
        'brand_voice' => null,
        'custom_instructions' => null,
        'prompt' => null,
        'aspect_ratio' => null,
        'count' => null,
        'quality' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'caption' => false,
        'platform' => false,
        'template' => false,
        'style' => false,
        'brand_voice' => false,
        'custom_instructions' => false,
        'prompt' => false,
        'aspect_ratio' => false,
        'count' => false,
        'quality' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'caption' => 'caption',
        'platform' => 'platform',
        'template' => 'template',
        'style' => 'style',
        'brand_voice' => 'brand_voice',
        'custom_instructions' => 'custom_instructions',
        'prompt' => 'prompt',
        'aspect_ratio' => 'aspect_ratio',
        'count' => 'count',
        'quality' => 'quality'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'caption' => 'setCaption',
        'platform' => 'setPlatform',
        'template' => 'setTemplate',
        'style' => 'setStyle',
        'brand_voice' => 'setBrandVoice',
        'custom_instructions' => 'setCustomInstructions',
        'prompt' => 'setPrompt',
        'aspect_ratio' => 'setAspectRatio',
        'count' => 'setCount',
        'quality' => 'setQuality'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'caption' => 'getCaption',
        'platform' => 'getPlatform',
        'template' => 'getTemplate',
        'style' => 'getStyle',
        'brand_voice' => 'getBrandVoice',
        'custom_instructions' => 'getCustomInstructions',
        'prompt' => 'getPrompt',
        'aspect_ratio' => 'getAspectRatio',
        'count' => 'getCount',
        'quality' => 'getQuality'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TEMPLATE_BLOG_COVER = 'blog_cover';
    public const TEMPLATE_QUOTE_CARD = 'quote_card';
    public const TEMPLATE_STAT_CARD = 'stat_card';
    public const TEMPLATE_FEATURE_ANNOUNCEMENT = 'feature_announcement';
    public const TEMPLATE_PRODUCT_HIGHLIGHT = 'product_highlight';
    public const TEMPLATE_EVENT_PROMO = 'event_promo';
    public const TEMPLATE_CAROUSEL_SLIDE = 'carousel_slide';
    public const TEMPLATE_AD_CREATIVE = 'ad_creative';
    public const ASPECT_RATIO__11 = '1:1';
    public const ASPECT_RATIO__169 = '16:9';
    public const ASPECT_RATIO__916 = '9:16';
    public const ASPECT_RATIO__45 = '4:5';
    public const QUALITY_STANDARD = 'standard';
    public const QUALITY_HD = 'hd';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTemplateAllowableValues()
    {
        return [
            self::TEMPLATE_BLOG_COVER,
            self::TEMPLATE_QUOTE_CARD,
            self::TEMPLATE_STAT_CARD,
            self::TEMPLATE_FEATURE_ANNOUNCEMENT,
            self::TEMPLATE_PRODUCT_HIGHLIGHT,
            self::TEMPLATE_EVENT_PROMO,
            self::TEMPLATE_CAROUSEL_SLIDE,
            self::TEMPLATE_AD_CREATIVE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAspectRatioAllowableValues()
    {
        return [
            self::ASPECT_RATIO__11,
            self::ASPECT_RATIO__169,
            self::ASPECT_RATIO__916,
            self::ASPECT_RATIO__45,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getQualityAllowableValues()
    {
        return [
            self::QUALITY_STANDARD,
            self::QUALITY_HD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('caption', $data ?? [], null);
        $this->setIfExists('platform', $data ?? [], null);
        $this->setIfExists('template', $data ?? [], null);
        $this->setIfExists('style', $data ?? [], null);
        $this->setIfExists('brand_voice', $data ?? [], null);
        $this->setIfExists('custom_instructions', $data ?? [], null);
        $this->setIfExists('prompt', $data ?? [], null);
        $this->setIfExists('aspect_ratio', $data ?? [], '1:1');
        $this->setIfExists('count', $data ?? [], 1);
        $this->setIfExists('quality', $data ?? [], 'standard');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['caption']) && (mb_strlen($this->container['caption']) > 2000)) {
            $invalidProperties[] = "invalid value for 'caption', the character length must be smaller than or equal to 2000.";
        }

        $allowedValues = $this->getTemplateAllowableValues();
        if (!is_null($this->container['template']) && !in_array($this->container['template'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'template', must be one of '%s'",
                $this->container['template'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['custom_instructions']) && (mb_strlen($this->container['custom_instructions']) > 1000)) {
            $invalidProperties[] = "invalid value for 'custom_instructions', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['prompt']) && (mb_strlen($this->container['prompt']) > 4000)) {
            $invalidProperties[] = "invalid value for 'prompt', the character length must be smaller than or equal to 4000.";
        }

        $allowedValues = $this->getAspectRatioAllowableValues();
        if (!is_null($this->container['aspect_ratio']) && !in_array($this->container['aspect_ratio'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'aspect_ratio', must be one of '%s'",
                $this->container['aspect_ratio'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['count']) && ($this->container['count'] > 4)) {
            $invalidProperties[] = "invalid value for 'count', must be smaller than or equal to 4.";
        }

        if (!is_null($this->container['count']) && ($this->container['count'] < 1)) {
            $invalidProperties[] = "invalid value for 'count', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getQualityAllowableValues();
        if (!is_null($this->container['quality']) && !in_array($this->container['quality'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'quality', must be one of '%s'",
                $this->container['quality'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets caption
     *
     * @return string|null
     */
    public function getCaption()
    {
        return $this->container['caption'];
    }

    /**
     * Sets caption
     *
     * @param string|null $caption Social media caption. Triggers standard mode. Takes priority over prompt.
     *
     * @return self
     */
    public function setCaption($caption)
    {
        if (is_null($caption)) {
            throw new \InvalidArgumentException('non-nullable caption cannot be null');
        }
        if ((mb_strlen($caption) > 2000)) {
            throw new \InvalidArgumentException('invalid length for $caption when calling ImageGenerateInput., must be smaller than or equal to 2000.');
        }

        $this->container['caption'] = $caption;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string|null
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string|null $platform Required when caption is provided.
     *
     * @return self
     */
    public function setPlatform($platform)
    {
        if (is_null($platform)) {
            throw new \InvalidArgumentException('non-nullable platform cannot be null');
        }
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets template
     *
     * @return string|null
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     *
     * @param string|null $template template
     *
     * @return self
     */
    public function setTemplate($template)
    {
        if (is_null($template)) {
            throw new \InvalidArgumentException('non-nullable template cannot be null');
        }
        $allowedValues = $this->getTemplateAllowableValues();
        if (!in_array($template, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'template', must be one of '%s'",
                    $template,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets style
     *
     * @return string|null
     */
    public function getStyle()
    {
        return $this->container['style'];
    }

    /**
     * Sets style
     *
     * @param string|null $style style
     *
     * @return self
     */
    public function setStyle($style)
    {
        if (is_null($style)) {
            throw new \InvalidArgumentException('non-nullable style cannot be null');
        }
        $this->container['style'] = $style;

        return $this;
    }

    /**
     * Gets brand_voice
     *
     * @return string|null
     */
    public function getBrandVoice()
    {
        return $this->container['brand_voice'];
    }

    /**
     * Sets brand_voice
     *
     * @param string|null $brand_voice brand_voice
     *
     * @return self
     */
    public function setBrandVoice($brand_voice)
    {
        if (is_null($brand_voice)) {
            throw new \InvalidArgumentException('non-nullable brand_voice cannot be null');
        }
        $this->container['brand_voice'] = $brand_voice;

        return $this;
    }

    /**
     * Gets custom_instructions
     *
     * @return string|null
     */
    public function getCustomInstructions()
    {
        return $this->container['custom_instructions'];
    }

    /**
     * Sets custom_instructions
     *
     * @param string|null $custom_instructions custom_instructions
     *
     * @return self
     */
    public function setCustomInstructions($custom_instructions)
    {
        if (is_null($custom_instructions)) {
            throw new \InvalidArgumentException('non-nullable custom_instructions cannot be null');
        }
        if ((mb_strlen($custom_instructions) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $custom_instructions when calling ImageGenerateInput., must be smaller than or equal to 1000.');
        }

        $this->container['custom_instructions'] = $custom_instructions;

        return $this;
    }

    /**
     * Gets prompt
     *
     * @return string|null
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string|null $prompt Developer escape hatch. Bypasses internal prompt builder. Ignored if caption is present.
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }
        if ((mb_strlen($prompt) > 4000)) {
            throw new \InvalidArgumentException('invalid length for $prompt when calling ImageGenerateInput., must be smaller than or equal to 4000.');
        }

        $this->container['prompt'] = $prompt;

        return $this;
    }

    /**
     * Gets aspect_ratio
     *
     * @return string|null
     */
    public function getAspectRatio()
    {
        return $this->container['aspect_ratio'];
    }

    /**
     * Sets aspect_ratio
     *
     * @param string|null $aspect_ratio aspect_ratio
     *
     * @return self
     */
    public function setAspectRatio($aspect_ratio)
    {
        if (is_null($aspect_ratio)) {
            throw new \InvalidArgumentException('non-nullable aspect_ratio cannot be null');
        }
        $allowedValues = $this->getAspectRatioAllowableValues();
        if (!in_array($aspect_ratio, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'aspect_ratio', must be one of '%s'",
                    $aspect_ratio,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['aspect_ratio'] = $aspect_ratio;

        return $this;
    }

    /**
     * Gets count
     *
     * @return int|null
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int|null $count count
     *
     * @return self
     */
    public function setCount($count)
    {
        if (is_null($count)) {
            throw new \InvalidArgumentException('non-nullable count cannot be null');
        }

        if (($count > 4)) {
            throw new \InvalidArgumentException('invalid value for $count when calling ImageGenerateInput., must be smaller than or equal to 4.');
        }
        if (($count < 1)) {
            throw new \InvalidArgumentException('invalid value for $count when calling ImageGenerateInput., must be bigger than or equal to 1.');
        }

        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets quality
     *
     * @return string|null
     */
    public function getQuality()
    {
        return $this->container['quality'];
    }

    /**
     * Sets quality
     *
     * @param string|null $quality quality
     *
     * @return self
     */
    public function setQuality($quality)
    {
        if (is_null($quality)) {
            throw new \InvalidArgumentException('non-nullable quality cannot be null');
        }
        $allowedValues = $this->getQualityAllowableValues();
        if (!in_array($quality, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'quality', must be one of '%s'",
                    $quality,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['quality'] = $quality;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


