<?php
/**
 * ImageGenerationResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PostBoostClient\Model;

use \ArrayAccess;
use \PostBoostClient\ObjectSerializer;

/**
 * ImageGenerationResponse Class Doc Comment
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ImageGenerationResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ImageGenerationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'images' => '\PostBoostClient\Model\Media[]',
        'prompt_used' => 'string',
        'revised_prompt' => 'string',
        'aspect_ratio' => 'string',
        'quality' => 'string',
        'credits_used' => 'int',
        'credits_remaining' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'images' => null,
        'prompt_used' => null,
        'revised_prompt' => null,
        'aspect_ratio' => null,
        'quality' => null,
        'credits_used' => null,
        'credits_remaining' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'images' => false,
        'prompt_used' => false,
        'revised_prompt' => false,
        'aspect_ratio' => false,
        'quality' => false,
        'credits_used' => false,
        'credits_remaining' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'images' => 'images',
        'prompt_used' => 'prompt_used',
        'revised_prompt' => 'revised_prompt',
        'aspect_ratio' => 'aspect_ratio',
        'quality' => 'quality',
        'credits_used' => 'credits_used',
        'credits_remaining' => 'credits_remaining'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'images' => 'setImages',
        'prompt_used' => 'setPromptUsed',
        'revised_prompt' => 'setRevisedPrompt',
        'aspect_ratio' => 'setAspectRatio',
        'quality' => 'setQuality',
        'credits_used' => 'setCreditsUsed',
        'credits_remaining' => 'setCreditsRemaining'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'images' => 'getImages',
        'prompt_used' => 'getPromptUsed',
        'revised_prompt' => 'getRevisedPrompt',
        'aspect_ratio' => 'getAspectRatio',
        'quality' => 'getQuality',
        'credits_used' => 'getCreditsUsed',
        'credits_remaining' => 'getCreditsRemaining'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('prompt_used', $data ?? [], null);
        $this->setIfExists('revised_prompt', $data ?? [], null);
        $this->setIfExists('aspect_ratio', $data ?? [], null);
        $this->setIfExists('quality', $data ?? [], null);
        $this->setIfExists('credits_used', $data ?? [], null);
        $this->setIfExists('credits_remaining', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['images'] === null) {
            $invalidProperties[] = "'images' can't be null";
        }
        if ($this->container['prompt_used'] === null) {
            $invalidProperties[] = "'prompt_used' can't be null";
        }
        if ($this->container['aspect_ratio'] === null) {
            $invalidProperties[] = "'aspect_ratio' can't be null";
        }
        if ($this->container['quality'] === null) {
            $invalidProperties[] = "'quality' can't be null";
        }
        if ($this->container['credits_used'] === null) {
            $invalidProperties[] = "'credits_used' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets images
     *
     * @return \PostBoostClient\Model\Media[]
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \PostBoostClient\Model\Media[] $images images
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets prompt_used
     *
     * @return string
     */
    public function getPromptUsed()
    {
        return $this->container['prompt_used'];
    }

    /**
     * Sets prompt_used
     *
     * @param string $prompt_used prompt_used
     *
     * @return self
     */
    public function setPromptUsed($prompt_used)
    {
        if (is_null($prompt_used)) {
            throw new \InvalidArgumentException('non-nullable prompt_used cannot be null');
        }
        $this->container['prompt_used'] = $prompt_used;

        return $this;
    }

    /**
     * Gets revised_prompt
     *
     * @return string|null
     */
    public function getRevisedPrompt()
    {
        return $this->container['revised_prompt'];
    }

    /**
     * Sets revised_prompt
     *
     * @param string|null $revised_prompt revised_prompt
     *
     * @return self
     */
    public function setRevisedPrompt($revised_prompt)
    {
        if (is_null($revised_prompt)) {
            throw new \InvalidArgumentException('non-nullable revised_prompt cannot be null');
        }
        $this->container['revised_prompt'] = $revised_prompt;

        return $this;
    }

    /**
     * Gets aspect_ratio
     *
     * @return string
     */
    public function getAspectRatio()
    {
        return $this->container['aspect_ratio'];
    }

    /**
     * Sets aspect_ratio
     *
     * @param string $aspect_ratio aspect_ratio
     *
     * @return self
     */
    public function setAspectRatio($aspect_ratio)
    {
        if (is_null($aspect_ratio)) {
            throw new \InvalidArgumentException('non-nullable aspect_ratio cannot be null');
        }
        $this->container['aspect_ratio'] = $aspect_ratio;

        return $this;
    }

    /**
     * Gets quality
     *
     * @return string
     */
    public function getQuality()
    {
        return $this->container['quality'];
    }

    /**
     * Sets quality
     *
     * @param string $quality quality
     *
     * @return self
     */
    public function setQuality($quality)
    {
        if (is_null($quality)) {
            throw new \InvalidArgumentException('non-nullable quality cannot be null');
        }
        $this->container['quality'] = $quality;

        return $this;
    }

    /**
     * Gets credits_used
     *
     * @return int
     */
    public function getCreditsUsed()
    {
        return $this->container['credits_used'];
    }

    /**
     * Sets credits_used
     *
     * @param int $credits_used credits_used
     *
     * @return self
     */
    public function setCreditsUsed($credits_used)
    {
        if (is_null($credits_used)) {
            throw new \InvalidArgumentException('non-nullable credits_used cannot be null');
        }
        $this->container['credits_used'] = $credits_used;

        return $this;
    }

    /**
     * Gets credits_remaining
     *
     * @return int|null
     */
    public function getCreditsRemaining()
    {
        return $this->container['credits_remaining'];
    }

    /**
     * Sets credits_remaining
     *
     * @param int|null $credits_remaining credits_remaining
     *
     * @return self
     */
    public function setCreditsRemaining($credits_remaining)
    {
        if (is_null($credits_remaining)) {
            throw new \InvalidArgumentException('non-nullable credits_remaining cannot be null');
        }
        $this->container['credits_remaining'] = $credits_remaining;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


