<?php
/**
 * SubscriptionStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PostBoostClient\Model;
use \PostBoostClient\ObjectSerializer;

/**
 * SubscriptionStatus Class Doc Comment
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubscriptionStatus
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'active';

    public const TRIALING = 'trialing';

    public const PAST_DUE = 'past_due';

    public const PAUSED = 'paused';

    public const CANCELED = 'canceled';

    public const INCOMPLETE = 'incomplete';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::TRIALING,
            self::PAST_DUE,
            self::PAUSED,
            self::CANCELED,
            self::INCOMPLETE
        ];
    }
}


