<?php
/**
 * WorkspacesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PostBoostClient\Test\Api;

use \PostBoostClient\Configuration;
use \PostBoostClient\ApiException;
use \PostBoostClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkspacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  PostBoostClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkspacesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addUserToWorkspace
     *
     * Add user to workspace.
     *
     */
    public function testAddUserToWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWorkspace
     *
     * Create workspace.
     *
     */
    public function testCreateWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWorkspace
     *
     * Delete workspace.
     *
     */
    public function testDeleteWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWorkspacesBulk
     *
     * Delete workspaces (bulk).
     *
     */
    public function testDeleteWorkspacesBulk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWorkspace
     *
     * Get workspace.
     *
     */
    public function testGetWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWorkspaces
     *
     * List workspaces.
     *
     */
    public function testListWorkspaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeUserFromWorkspace
     *
     * Remove user from workspace.
     *
     */
    public function testRemoveUserFromWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWorkspace
     *
     * Update workspace.
     *
     */
    public function testUpdateWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWorkspaceUser
     *
     * Update user role in workspace.
     *
     */
    public function testUpdateWorkspaceUser()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
